# Generated by Django 4.1.7 on 2023-03-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
                ('completed', models.BooleanField(default=False, verbose_name='Complete ?')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['completed', 'created_at'],
            },
        ),
    ]
